#!/bin/sh
#
# Node Setup


# Install node and npm (check first)
if test ! $(which node)
then
  brew install node
else
  echo "  + Node found"
fi

if test ! $(which npm)
then
  brew install npm
else
  echo "  + NPM found"
fi



# Install commonly used modules
npm install -g bower
npm install -g express
npm install -g aws-lib
npm install -g s3
npm install -g mongoose
npm install -g webshot
npm install -g less
npm install -g imagemagick
npm install -g grunt
npm install -g brisk
npm install -g crudr
npm install -g uglify-js
npm install -g imageoptim-cli
npm install -g bower-installer
npm install -g localtunnel